# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: VCListPack.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Data",
    "Metadata",
    "Questions",
    "WordEmbedding",
)

from dataclasses import dataclass

import betterproto2

from .message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class Data(betterproto2.Message):
    metadata: "Metadata | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    deduplicated_strings: "list[str]" = betterproto2.field(
        2, betterproto2.TYPE_STRING, repeated=True
    )

    embeddings: "list[WordEmbedding]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )

    questions: "list[Questions]" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("", "Data", Data)


@dataclass(eq=False, repr=False)
class Metadata(betterproto2.Message):
    version: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    list_id: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    producer: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)


default_message_pool.register_message("", "Metadata", Metadata)


@dataclass(eq=False, repr=False)
class Questions(betterproto2.Message):
    question_text: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    contextual_sentence: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    answers: "list[int]" = betterproto2.field(3, betterproto2.TYPE_INT32, repeated=True)

    correct_answer_index: "int" = betterproto2.field(4, betterproto2.TYPE_INT32)

    target_word: "int" = betterproto2.field(5, betterproto2.TYPE_INT32)


default_message_pool.register_message("", "Questions", Questions)


@dataclass(eq=False, repr=False)
class WordEmbedding(betterproto2.Message):
    word: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    embedding: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)


default_message_pool.register_message("", "WordEmbedding", WordEmbedding)
